

sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install meson; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:latest; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t mvaldina_h264lens .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run mvaldina_h264lens /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson builddir && ninja -C builddir test"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then SDKROOT=$(xcodebuild -version -sdk macosx Path) meson builddir && ninja -C builddir test; fi