sudo: required
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install meson

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test